benchmarks:
- php_php-fuzz-execute
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: php-exp4
experiment_filestore: /tmp/experiment-data
fuzzers:
- gramatron
- nautilus
- gramatron-fix
- nautilus-large
git_hash: f0ec3df022a1b96f0bb4f5d9d3c4da6a1c6e1b89
local_experiment: true
max_total_time: 86400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 1
