benchmarks:
- php_php-fuzz-execute
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: php-cmp2
experiment_filestore: /tmp/experiment-data
fuzzers:
- nautilus_large
- nautilus_large_deep
- nautilus
- gramatron
- gramatron_fix
- nautilus_deep
git_hash: 22d73fde91ba4aa17eb14611092469690aa84d34
local_experiment: true
max_total_time: 86400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 2
