benchmarks:
- php_php-fuzz-execute
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: php-exp2
experiment_filestore: /tmp/experiment-data
fuzzers:
- gramatron
- nautilus
git_hash: 183ddc24acc8da49b11f938e3f7428d881dbbf59
local_experiment: true
max_total_time: 86400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 5
