benchmarks:
- php_php-fuzz-execute
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: php-exp5
experiment_filestore: /tmp/experiment-data
fuzzers:
- gramatron_fix
git_hash: 8b1c83f012f5630469c19266978bb52997d669bc
local_experiment: true
max_total_time: 86400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 1
